# Generated by Django 5.1.3 on 2024-11-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wispar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(choices=[('Audiobook', 'Audiobook'), ('Ebook', 'Ebook')], max_length=10)),
                ('isbn', models.CharField(max_length=17)),
                ('publication_date', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('filepath', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'books',
                'constraints': [models.UniqueConstraint(fields=('bookId', 'isbn'), name='book_constraint')],
            },
        ),
    ]
