# Generated by Django 5.1.3 on 2024-11-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wispar', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='filepath',
        ),
        migrations.AddField(
            model_name='book',
            name='filefield',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
