# Generated by Django 5.1.3 on 2024-11-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wispar', '0004_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=50),
        ),
    ]
