# Generated by Django 5.1.3 on 2024-11-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wispar', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='linked_medium',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
