# Generated by Django 5.1.3 on 2024-11-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wispar', '0006_book_linked_medium'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='book_constraint',
        ),
    ]
