# Generated by Django 5.1.3 on 2025-01-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wispar', '0007_remove_book_book_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='filefield',
            field=models.FileField(max_length=511, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=511),
        ),
    ]
