# Generated by Django 5.1.3 on 2025-01-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wispar', '0009_titlelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlelocation',
            name='book_id',
            field=models.IntegerField(default=1),
        ),
    ]
