# Generated by Django 5.1.3 on 2025-02-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0011_personalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlelocation",
            name="progress_percentage",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="titlelocation",
            name="audio_location",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="titlelocation",
            name="text_location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
