# Generated by Django 5.1.3 on 2025-02-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0012_titlelocation_progress_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlelocation",
            name="last_read_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
