# Generated by Django 5.1.3 on 2025-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0013_titlelocation_last_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalsettings",
            name="library_visible",
            field=models.BooleanField(default=True),
        ),
    ]
