# Generated by Django 5.1.3 on 2025-02-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0014_personalsettings_library_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalsettings",
            name="curved_radius",
            field=models.BooleanField(default=True),
        ),
    ]
