# Generated by Django 5.1.3 on 2025-02-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0015_personalsettings_curved_radius"),
        ("wispar", "0015_personalsettings_ui_font"),
    ]

    operations = []
