# Generated by Django 5.1.3 on 2025-03-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0016_merge_20250226_0206"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalsettings",
            name="custom_epub_default",
            field=models.BooleanField(default=False),
        ),
    ]
