# Generated by Django 5.1.3 on 2025-03-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0017_personalsettings_custom_epub_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlelocation",
            name="location_text_snippet",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="titlelocation",
            name="bookmark_type",
            field=models.CharField(
                choices=[
                    ("custom_bookmark", "cfi"),
                    ("highlight", "cfi"),
                    ("last_read_position", "last_read_position"),
                ],
                max_length=18,
            ),
        ),
    ]
