# Generated by Django 5.1.3 on 2025-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0018_titlelocation_location_text_snippet_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalsettings",
            old_name="recent_releases_visible",
            new_name="recent_release_visible",
        ),
        migrations.AddField(
            model_name="personalsettings",
            name="recently_read_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="personalsettings",
            name="row_order",
            field=models.CharField(
                default="recently_read,recently_added,recent_release,library",
                max_length=255,
            ),
        ),
    ]
