# Generated by Django 5.1.3 on 2025-03-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wispar",
            "0019_rename_recent_releases_visible_personalsettings_recent_release_visible_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationToggle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users_can_register", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "registration_toggle",
            },
        ),
    ]
