# Generated by Django 5.1.3 on 2025-04-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0021_contentrestrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlelocation",
            name="time_remaining",
            field=models.IntegerField(default=-1),
        ),
    ]
