# Generated by Django 5.1.3 on 2025-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0022_titlelocation_time_remaining"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("existingPath", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("eof", models.BooleanField()),
            ],
        ),
    ]
