# Generated by Django 5.1.3 on 2025-04-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0023_tempfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titlelocation",
            name="vtt_location",
        ),
        migrations.AlterField(
            model_name="titlelocation",
            name="bookmark_type",
            field=models.CharField(
                choices=[
                    ("bookmark", "cfi"),
                    ("highlight", "cfi"),
                    ("last_read_position", "last_read_position"),
                ],
                max_length=18,
            ),
        ),
    ]