# Generated by Django 5.1.3 on 2025-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wispar", "0024_remove_titlelocation_vtt_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempfile",
            name="existingPath",
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name="tempfile",
            name="name",
            field=models.CharField(max_length=511),
        ),
    ]
